# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/common/xilinx/adi_fir_filter_constr.xdc

# XDC: /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/system_constr.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cmos_tx_0/system_axi_cmos_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cmos_tx_0 || ORIG_REF_NAME==system_axi_cmos_tx_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ram_shift_reg0/ram_shift_reg0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_shift_reg0 || ORIG_REF_NAME==ram_shift_reg0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_power_0 || ORIG_REF_NAME==system_axi_gpio_power_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_0/system_cdc_sync_active_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_0 || ORIG_REF_NAME==system_cdc_sync_active_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_gen_0/system_rate_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rate_gen_0 || ORIG_REF_NAME==system_rate_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_0_0/system_fir_interpolation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_0_0 || ORIG_REF_NAME==system_fir_interpolation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_0_0/system_logic_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_0_0 || ORIG_REF_NAME==system_logic_and_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_0/system_out_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_0_0 || ORIG_REF_NAME==system_out_mux_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_interpolation_1_0 || ORIG_REF_NAME==system_fir_interpolation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_1_0/system_logic_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_and_1_0 || ORIG_REF_NAME==system_logic_and_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_0/system_out_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_1_0 || ORIG_REF_NAME==system_out_mux_1_0} -quiet] -quiet

# IP: bd/system/ip/system_VCC_1_0/system_VCC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_VCC_1_0 || ORIG_REF_NAME==system_VCC_1_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_32_0/system_GND_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GND_32_0 || ORIG_REF_NAME==system_GND_32_0} -quiet] -quiet

# IP: bd/system/ip/system_interp_slice_0/system_interp_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_interp_slice_0 || ORIG_REF_NAME==system_interp_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_upack_0/system_tx_upack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tx_upack_0 || ORIG_REF_NAME==system_tx_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_1/system_cdc_sync_active_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_1 || ORIG_REF_NAME==system_cdc_sync_active_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_0_0/system_fir_decimation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_0_0 || ORIG_REF_NAME==system_fir_decimation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_1/system_out_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_0_1 || ORIG_REF_NAME==system_out_mux_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_1_0/system_fir_decimation_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fir_decimation_1_0 || ORIG_REF_NAME==system_fir_decimation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_1/system_out_mux_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_out_mux_1_1 || ORIG_REF_NAME==system_out_mux_1_1} -quiet] -quiet

# IP: bd/system/ip/system_decim_slice_0/system_decim_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_decim_slice_0 || ORIG_REF_NAME==system_decim_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_cpack_0/system_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cpack_0 || ORIG_REF_NAME==system_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_or_0/system_logic_or_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_or_0 || ORIG_REF_NAME==system_logic_or_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_0_0/system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc

# XDC: bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_power_0 || ORIG_REF_NAME==system_axi_gpio_power_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_power_0 || ORIG_REF_NAME==system_axi_gpio_power_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/ad_rst_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_0_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_0_0 || ORIG_REF_NAME==system_fir_interpolation_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_interpolation_1_0 || ORIG_REF_NAME==system_fir_interpolation_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_0_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_0_0 || ORIG_REF_NAME==system_fir_decimation_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_fir_decimation_1_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fir_decimation_1_0 || ORIG_REF_NAME==system_fir_decimation_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
