# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param messaging.defaultLimit 2000
set_param synth.elaboration.rodinMoreOptions {rt::set_parameter var_size_limit 4194304}
set_msg_config -id {33-285} -limit 100
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -id {Designutils 20-3303}  -string {{HDPYFinalizeIO}}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.cache/wt [current_project]
set_property parent.project_path /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library
  /home/myh/Documents/antsdr/antsdr-fw_radar/ghdl/library
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library/util_fir_int/coefile_int.coe
read_verilog -library xil_defaultlib {
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library/util_cdc/sync_bits.v
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library/common/util_pulse_gen.v
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library/common/ad_bus_mux.v
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/library/common/ad_iobuf.v
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/imports/hdl/system_wrapper.v
  /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/system_top.v
}
add_files /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/system.bd
set_property is_enabled false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_synthesis false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_cmos_tx_0/axi_ad9361_cmos_tx.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_spi_0/system_axi_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_gpio_power_0/system_axi_gpio_power_0.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_fir_interpolation_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_fir_decimation_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_fir_decimation_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_synthesis false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/common/xilinx/adi_fir_filter_constr.xdc
set_property used_in_implementation false [get_files /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/common/xilinx/adi_fir_filter_constr.xdc]

read_xdc /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/system_constr.xdc
set_property used_in_implementation false [get_files /home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
