set_property SRC_FILE_INFO {cfile:/home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/system_constr.xdc rfile:../../../system_constr.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc rfile:../../../ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc id:2 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_dac_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/myh/Documents/antsdr/antsdr-fw_radar/hdl/projects/ant/ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc rfile:../../../ant.srcs/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc id:3 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9361_adc_dma/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports gpio_en_agc]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports gpio_resetb]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports {gpio_ctl[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports {gpio_ctl[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {gpio_ctl[2]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports {gpio_ctl[3]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports {gpio_status[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {gpio_status[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {gpio_status[2]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {gpio_status[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports {gpio_status[4]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports {gpio_status[5]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports {gpio_status[6]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {gpio_status[7]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports rx_clk_in]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports rx_frame_in]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {rx_data_in[0]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports {rx_data_in[1]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {rx_data_in[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {rx_data_in[3]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports {rx_data_in[4]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {rx_data_in[5]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports {rx_data_in[6]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {rx_data_in[7]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {rx_data_in[8]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {rx_data_in[9]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {rx_data_in[10]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {rx_data_in[11]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {tx_data_out[0]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {tx_data_out[1]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {tx_data_out[2]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports {tx_data_out[3]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {tx_data_out[4]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {tx_data_out[5]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {tx_data_out[6]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {tx_data_out[7]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {tx_data_out[8]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {tx_data_out[9]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {tx_data_out[10]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {tx_data_out[11]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports tx_clk_out]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports tx_frame_out]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports txnrx]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports clk_out]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports enable]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports spi_csn]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports spi_clk]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports pl_spi_clk_o]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports pl_spi_miso]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports pl_spi_mosi]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports iic_scl]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports iic_sda]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports VCRX1_H]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports VCRX1_L]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports VCTX1_H]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports VCTX1_L]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports VCRX2_H]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports VCRX2_L]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports VCTX2_H]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports VCTX2_L]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9 [get_ports powerctrl[0]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11 [get_ports powerctrl[1]]
current_instance i_system_wrapper/system_i/axi_ad9361_dac_dma/inst
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_req_response_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_response_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_response_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_dac_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance i_system_wrapper/system_i/axi_ad9361_adc_dma/inst
set_property src_info {type:SCOPED_XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_src_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_src_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_rewind_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_rewind_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_sync_dest_request_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_dest_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_store_and_forward/i_src_sync_id* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier -filter {IS_SEQUENTIAL && NAME =~ *i_store_and_forward/burst_len_mem_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_dest_req_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_dest_req_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_waddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] -to [get_cells -quiet -hier *cdc_sync_stage1_reg* -filter {NAME =~ *i_src_dest_bl_fifo/i_raddr_sync* && IS_SEQUENTIAL}] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_cells -quiet -hier *cdc_sync_fifo_ram_reg* -filter {NAME =~ *i_src_dest_bl_fifo* && IS_SEQUENTIAL}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
set_property src_info {type:SCOPED_XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -quiet -datapath_only -from [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_wr_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_src_axi_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/s_axis_aclk]]] -through [get_cells -quiet -hier DP -filter {NAME =~ *i_request_arb/eot_mem_dest_reg*}] -to [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]] [get_property -min PERIOD [get_clocks -of_objects [get_pins [list i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/fifo_rd_clk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_axis_aclk i_system_wrapper/system_i/axi_ad9361_adc_dma/inst/m_dest_axi_aclk]]]]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.RX_FIFO_II/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance i_system_wrapper/system_i/axi_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/FIFO_EXISTS.TX_FIFO_II/xpm_fifo_instance.xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
